fed:
    fed_mode: FedAvg
    seed: 1
    run_seed: 1
    init_seed: 1
    gpu: 0
    host: 127.0.0.1
    port: 9291

model:
    model_name: resnet50_unet
    model_mode: seg
    ptr_weights: imagenet
    amp: false

    num_workers: 0
    num_channels: 3
    num_classes: 5

optimizer:
    type: SGD
    lr: 1e-2
    momentum: 0.9
    weight_decay: 5e-4

lr_schedule:
    mode: cos
    min_lr: 1e-5
    iter_step: false

dataset:
    dataset_name: TJDR
    img_size: 1024

    slide_inference:
      slide_crop_size: 224
      slide_stride: 112

    data_augment: true
    drop_split: 0.6

    dataset_dir:
        train: datas/TJDR/train
        test: datas/TJDR/test

    ignore_label: 255

client:
    epoch: 1
    batch_size: 8
    eval_batch_size: 8
    log_iter: 100

    client_eval:
        test:
            num: 0

edge:
    epoch: 2000 # for c1-c4 and separate
#    epoch: 1   # for fedavg
    num_clients: 1
    save_ckpt_epoch: 0

    edge_eval:
        test:
            num: 100  # for c1-c4 and separate
#            num: 0   # for fedavg
            metric: [mIoU,mDice]

cloud:
    epoch: 1  # for c1-c4 and separate
#    epoch: 2000   # for fedavg
    num_edges: 4 # for c1-c4 and fedavg
#    num_edges: 1 # for separate
    save_ckpt_epoch: 0

    cloud_eval:
        test:
            num: 0   # for c1-c4 and separate
#            num: 100 # for fedavg
            metric: [mIoU,mDice]