fed:
    fed_mode: FedAvg
    seed: 2
    run_seed: 2
    init_seed: 1
    gpu: 0
    host: 127.0.0.1
    port: 9191

model:
    model_name: resnet50
    model_mode: cnn
    ptr_weights: imagenet
    dropout: 0.3
    amp: false

    num_workers: 0
    num_channels: 3
    num_classes: 5

optimizer:
    type: Adam
    lr: 1e-3
    momentum: 0.9
    weight_decay: 1e-3

lr_schedule:
    mode: poly
    min_lr: 0
    iter_step: false

dataset:
    dataset_name: APTOS2019
    img_size: 256

    data_augment: false

    non_iid:
        enable: true
        gamma: 0.8

    dataset_dir:
        train: datas/APTOS2019/train
        val: datas/APTOS2019/val

client:
    epoch: 1 # for fedavg
#    epoch: 200 # for c1-c4
    batch_size: 48
    eval_batch_size: 48
    log_iter: 100

    client_eval:
        val:
            num: 0 # for fedavg
#            num: 5 # for c1-c4
            metric: [mF1,mAcc]

edge:
    epoch: 200 # for fedavg
#    epoch: 1   # for c1-c4
    num_clients: 4
    save_ckpt_epoch: 0

    edge_eval:
        val:
            num: 5 # for fedavg
#            num: 0 # for c1-c4
            metric: [mF1,mAcc]
    tolerate:
        val:
            num: 5
            metric: mF1
            delta: 0.5

cloud:
    epoch: 1
    num_edges: 1
    save_ckpt_epoch: 0

    cloud_eval:
        val:
            num: 0
            metric: [mF1,mAcc]